### ISSUE TITLE
Are you open to pull requests?

### ISSUE THREAD

**Issue by onstash** [amoghpj/swar-synthesizer#1]
Hi Amogh. This project of yours seems interesting. Are you open to pull requests?

**Comment by amoghpj** [comment]
Sure thing man! I am no coder, so don't expect PEP8 compliance just yet haha. (That said, please let me know how I can cleanup stuff!)

**Comment by onstash** [comment]
Documentation strings could be added to the methods / functions that you have written so that it's easier to understand. For example 
```
def foo(a, b):
    """
    This function does something.
    :param a: Description of 'a'
    :type    a: type(a)
    :param b: Description of 'b'
    :type .  b: type(b)
    """
```

**Comment by onstash** [comment]
I am not going for PEP8 compliance. 😅 I am attempting to make the repository more accessible. 😄

**Comment by onstash** [comment]
In this method [`swar2freq`](https://github.com/amoghpj/swar-synthesizer/blob/903029f3ef62fe7ab6e396d8e249d0e64ae65c59/src/swar_synthesizer.py#L7), multiple calls of `float(basefreq)`. It can be replaced by assigning the `float(basefreq)` call to a variable and using it.

**Comment by amoghpj** [comment]
Commit 341eed0351d5e5af472d7b67952cccb0451a3675 adds function documentation and defines variable  for `float(basefreq)`
